version: '3'
services:
    angular-client:
        stdin_open: true
        build:
            context: ../atm-angular-client
            dockerfile: Dockerfile.dev
        ports:
            - "4200:4200"
        volumes:
            - /app/node_modules
            - .:/app